name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
  # https://dev.to/github/publishing-a-docker-image-to-githubs-container-repository-4n50
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build the Docker image
        run: |
          docker build ./voice_message_backend -f voice_message_backend/Dockerfile --tag ghcr.io/nahu02/bettervoicemessage-backend:latest
          docker push ghcr.io/nahu02/bettervoicemessage-backend:latest